version: "3.8"

services:
  app:
    container_name: app-dev
    image: app-dev
    tty: true
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 5000:5000